services:
    db:
        image: docker.io/postgres
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./db/:/docker-entrypoint-initdb.d/:ro
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/db_password
        secrets:
            - db_password

    phpserver:
        build: .
        depends_on:
            - db
        environment:
            POSTGRES_HOST: db
            POSTGRES_PASSWORD_FILE: /run/secrets/db_password
        secrets:
            - db_password
        volumes:
            - ./src/:/var/www/html:ro
            - logs:/var/www/logs

    nginx:
        image: docker.io/nginx
        restart: always
        ports:
            - 8080:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./src/:/var/www/html:ro
            - ./public/:/var/www/public:ro
            - logs:/var/www/logs
        depends_on:
            - phpserver

secrets:
    db_password:
        environment: POSTGRES_PASSWORD

volumes:
    db-data:
    logs:
