services:
    db:
        image: docker.io/postgres
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./db/:/docker-entrypoint-initdb.d/:ro
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/db_password
        secrets:
            - db_password

    phpserver:
        build:
            context: .
            dockerfile: php.Dockerfile
        depends_on:
            - db
        environment:
            POSTGRES_HOST: db
            POSTGRES_PASSWORD_FILE: /run/secrets/db_password
        secrets:
            - db_password
        volumes:
            - ./src/:/var/www/html:ro
            - logs:/var/www/logs

    nginx:
        build:
            context: .
            dockerfile: nginx.Dockerfile
        restart: always
        ports:
            - 8080:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./src/:/var/www/html:ro
            - ./public/:/var/www/public/:ro
            - logs:/var/www/logs
        depends_on:
            - phpserver

    assets:
        build:
            context: .
            dockerfile: nginx.Dockerfile
            target: assets
        user: node
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app
        # pnpm run dev alone is not enough due to this issue: https://github.com/tailwindlabs/tailwindcss/issues/18540
        # currently, we have to run compose down and up again after modifying the css
        # if this is solved in the future, remove the build command and use `command: pnpm run dev`
        command: "pnpm run build && pnpm run dev"

secrets:
    db_password:
        environment: POSTGRES_PASSWORD

volumes:
    db-data:
    logs:
